# create ec2 instance
AWSTemplateFormatVersion: "2010-09-09"

Description: Simple example how to create VPC
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true 
      Tags:
      - Key: Name
        Value: myTestVPC
